In [1]:
import warnings
import pandas as pd
from pandas.core.common import SettingWithCopyWarning
import numpy as np
import json

In [2]:
pd.options.display.max_rows = 999
pd.options.display.max_columns=999
warnings.simplefilter(action="ignore", category=SettingWithCopyWarning)

In [3]:

## parametros

# Opções de variação: “Resumido”
# Empresa: 1001 e 1005
# Planta: Todas
# Data Lançamento: 31.10.2021
# Material: 21, 22, 23, 24, 25, 26, 27, 28, 29 e 5046
# Conta corrente: Todas

In [4]:

#arquivoSAPBW = 'C:\\Temp\\ZTMM004_CCV\\DA_MM019.20221121.175050'  # 1 Total Registros Arquivo: 28473
#arquivoSAPBW = 'C:\\Temp\\ZTMM004_CCV\\DA_MM019.20221122.160951' # 2 Total Registros Arquivo: 27126
#arquivoSAPBW = 'C:\\Temp\\ZTMM004_CCV\\DA_MM019.20221122.173700' # 3 Total Registros Arquivo: 27124
arquivoSAPBW = 'C:\\Temp\\ZTMM004_CCV\\DA_MM019.20221123.101428' # 4 Total Registros Arquivo: 28472


dfZTMM004_SAPBW = pd.read_csv(arquivoSAPBW, sep=';',usecols=[1,2,3,4,10,11],header=None,skiprows=0
                              ,names=['CodCentro'
                                      ,'CodContaCorrente'
                                      ,'CodMaterial'
                                      ,'CodCliente'
                                      ,'Qtd'
                                      ,'Vlr']
                                 ,dtype={'CodCentro':'str'
                                         ,'CodContaCorrente':'str'
                                         ,'CodMaterial':'str'
                                         ,'CodCliente':'str'
                                         ,'Qtd':'str'
                                         ,'Vlr':'str'})

dfZTMM004_SAPBW['CodCliente'].fillna('0',inplace=True)

dfZTMM004_SAPBW['CodCliente'] = dfZTMM004_SAPBW['CodCliente'].astype(str).str.zfill(10) 

dfZTMM004_SAPBW['Chave'] = dfZTMM004_SAPBW['CodContaCorrente'] \
                                + '_' + dfZTMM004_SAPBW['CodMaterial'] \
                                + '_' + dfZTMM004_SAPBW['CodCentro'] \
                                + '_' + dfZTMM004_SAPBW['CodCliente']



dfZTMM004_SAPBW['ValidaQtd'] = (dfZTMM004_SAPBW['Qtd'].astype(str).str.contains('-').replace('-','')*-1)

dfZTMM004_SAPBW.loc[dfZTMM004_SAPBW['ValidaQtd'] == '-1','ValidaQtd'] = -1
dfZTMM004_SAPBW.loc[dfZTMM004_SAPBW['ValidaQtd'] == 0,'ValidaQtd'] = 1

dfZTMM004_SAPBW['Qtd'] = (dfZTMM004_SAPBW['Qtd'].astype(str).str.replace('-','')).astype(float) * (dfZTMM004_SAPBW['ValidaQtd']).astype(float)

dfZTMM004_SAPBW['ValidaVlr'] = (dfZTMM004_SAPBW['Vlr'].astype(str).str.contains('-').replace('-','')*-1)

dfZTMM004_SAPBW.loc[dfZTMM004_SAPBW['ValidaVlr'] == '-1','ValidaVlr'] = -1
dfZTMM004_SAPBW.loc[dfZTMM004_SAPBW['ValidaVlr'] == 0,'ValidaVlr'] = 1

dfZTMM004_SAPBW['Vlr'] = (dfZTMM004_SAPBW['Vlr'].astype(str).str.replace('-','')).astype(float) * (dfZTMM004_SAPBW['ValidaVlr']).astype(float)

dfZTMM004_SAPBW.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28472 entries, 0 to 28471
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CodCentro         28472 non-null  object
 1   CodContaCorrente  28472 non-null  object
 2   CodMaterial       28472 non-null  object
 3   CodCliente        28472 non-null  object
 4   Qtd               28472 non-null  float64
 5   Vlr               28472 non-null  float64
 6   Chave             28472 non-null  object
 7   ValidaQtd         28472 non-null  int32
 8   ValidaVlr         28472 non-null  int32
dtypes: float64(2), int32(2), object(5)
memory usage: 1.7+ MB

In [5]:
#fZTMM004_SAPBW[dfZTMM004_SAPBW['CodCliente']=='0001005118'].head(10)

In [6]:
#dfZTMM004_SAPBW[dfZTMM004_SAPBW['CodCliente']=='0001005118'].head(10)

In [7]:
# ARQUIVO DO DIA ZTMM004_CCV\\DA_MM019.20221116.133309
#dfZTMM004_SAPBW.info()

In [8]:
#dfZTMM004_SAPBW['CodMaterial'].unique()
# ARQUIVO DO DIA ZTMM004_CCV\\DA_MM019.20221116.133309
#dfZTMM004_SAPBW[dfZTMM004_SAPBW['Chave']=='013_000000000000000024_1011_0000001111'].sort_values(by='CodCliente')

In [9]:
# ARQUIVO DO DIA ZTMM004_CCV\\DA_MM019.20221121.175050
#dfZTMM004_SAPBW.info()

In [10]:
#dfZTMM004_SAPBW['CodMaterial'].unique()
# ARQUIVO DO DIA ZTMM004_CCV\\DA_MM019.20221121.175050
#dfZTMM004_SAPBW[dfZTMM004_SAPBW['Chave']=='013_000000000000000024_1011_0000001111'].sort_values(by='CodCliente')

In [11]:
#dfZTMM004_SAPBW

In [12]:
#dfZTMM004_SAPBW['CodMaterial'].unique()

#dfZTMM004_SAPBW[(dfZTMM004_SAPBW['CodContaCorrente']=='016')].groupby(['CodContaCorrente']).agg(Qtd=('Qtd','count'))

In [13]:
#dfZTMM004_SAPBW['CodMaterial'].unique()

#dfZTMM004_SAPBW[(dfZTMM004_SAPBW['CodContaCorrente']=='016')].groupby(['CodContaCorrente']).agg(Qtd=('Qtd','count'))

In [14]:
#dfZTMM004_SAPBW['CodMaterial'].unique()

#dfZTMM004_SAPECC[(dfZTMM004_SAPECC['CodContaCorrente']=='002') 
#                & (dfZTMM004_SAPECC['CodMaterial']=='000000000000000024')].groupby(['CodContaCorrente']).agg(Qtd=('Qtd','sum'))

In [15]:
#dfZTMM004_SAPBW['CodMaterial'].unique()

#dfZTMM004_SAPECC[(dfZTMM004_SAPECC['CodContaCorrente']=='002') 
#                & (dfZTMM004_SAPECC['CodMaterial']=='000000000000000021')]

In [16]:
#dfZTMM004_SAPBW['CodContaCorrente'].unique()

In [17]:
dfZTMM004_SAPBW = dfZTMM004_SAPBW.groupby(['CodCentro'
                         ,'CodContaCorrente'
                         ,'CodMaterial'
                         ,'CodCliente'
                         ,'Chave'],as_index=False).agg(Qtd=('Qtd','sum',),Vlr=('Vlr','sum'))

In [18]:
arquivoSAPECC = 'C:\\Temp\\ZTMM004_CCV\\exportZTMM004_20211031.XLSX'

dfZTMM004_SAPECC = pd.read_excel(arquivoSAPECC
                                 ,usecols=[0,2,4,5,7,8]
                                 ,names=['CodContaCorrente'
                                        ,'CodMaterial'
                                        ,'CodCentro'
                                        ,'CodCliente'
                                        ,'Qtd'
                                        ,'Vlr']
                                 ,dtype={'CodContaCorrente':'str'
                                         ,'CodMaterial':'str'
                                         ,'CodCentro':'str'
                                         ,'CodCliente':'str'
                                         ,'Qtd':'float'
                                         ,'Vlr':'float'})


dfZTMM004_SAPECC['CodCliente'].fillna('0',inplace=True)

dfZTMM004_SAPECC['Qtd'].fillna(0.0,inplace=True)
dfZTMM004_SAPECC['Vlr'].fillna(0.0,inplace=True)

dfZTMM004_SAPECC['CodContaCorrente'] = dfZTMM004_SAPECC['CodContaCorrente'].astype(str).str.zfill(3) 

dfZTMM004_SAPECC['CodCliente'] = dfZTMM004_SAPECC['CodCliente'].astype(str).str.zfill(10) 

dfZTMM004_SAPECC['Chave'] = dfZTMM004_SAPECC['CodContaCorrente'] \
                                + '_' + dfZTMM004_SAPECC['CodMaterial'] \
                                + '_' + dfZTMM004_SAPECC['CodCentro'] \
                                + '_' + dfZTMM004_SAPECC['CodCliente']


dfZTMM004_SAPECC = dfZTMM004_SAPECC.groupby(['CodCentro'
                         ,'CodContaCorrente'
                         ,'CodMaterial'
                         ,'CodCliente'
                         ,'Chave'],as_index=False).agg(Qtd=('Qtd','sum')
                                                       ,Vlr=('Vlr','sum'))

dfZTMM004_SAPECC.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26502 entries, 0 to 26501
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CodCentro         26502 non-null  object
 1   CodContaCorrente  26502 non-null  object
 2   CodMaterial       26502 non-null  object
 3   CodCliente        26502 non-null  object
 4   Chave             26502 non-null  object
 5   Qtd               26502 non-null  float64
 6   Vlr               26502 non-null  float64
dtypes: float64(2), object(5)
memory usage: 1.4+ MB

In [19]:
#dfZTMM004_SAPECC['CodContaCorrente'].unique()

#dfZTMM004_SAPECC[(dfZTMM004_SAPECC['CodContaCorrente']=='006')
#                & ( dfZTMM004_SAPECC['CodMaterial']=='000000000000000024')
#                & ( dfZTMM004_SAPECC['CodCentro']== '1011')].sort_values(by='CodCliente',ascending=True)

In [20]:
#dfZTMM004_SAPECC['CodContaCorrente'].unique()

dfZTMM004_SAPBW[(dfZTMM004_SAPBW['CodContaCorrente']=='100')
                & ( dfZTMM004_SAPBW['CodMaterial']=='000000000000000021')
                & ( dfZTMM004_SAPBW['CodCentro']== '1011')].sort_values(by='CodCliente',ascending=True)

,CodCentro,CodContaCorrente,CodMaterial,CodCliente,Chave,Qtd,Vlr
498,1011,100,000000000000000021,0000000000,100_000000000000000021_1011_0000000000,-10.0,0.0
499,1011,100,000000000000000021,00000D1011,100_000000000000000021_1011_00000D1011,13.0,0.0

In [21]:
dfZTMM004_SAPECC[dfZTMM004_SAPECC['Chave']=='100_000000000000000021_1011_0000000000']

,CodCentro,CodContaCorrente,CodMaterial,CodCliente,Chave,Qtd,Vlr
485,1011,100,000000000000000021,0000000000,100_000000000000000021_1011_0000000000,-10.0,0.0

In [22]:
dfZTMM004_SAPBW[(dfZTMM004_SAPBW['CodContaCorrente']=='100')
               & (dfZTMM004_SAPBW['CodMaterial']=='000000000000000021')]

,CodCentro,CodContaCorrente,CodMaterial,CodCliente,Chave,Qtd,Vlr
498,1011,100,000000000000000021,0000000000,100_000000000000000021_1011_0000000000,-10.0,0.00
499,1011,100,000000000000000021,00000D1011,100_000000000000000021_1011_00000D1011,13.0,0.00
1427,1012,100,000000000000000021,0000000000,100_000000000000000021_1012_0000000000,64.0,0.00
1428,1012,100,000000000000000021,00000D1012,100_000000000000000021_1012_00000D1012,-64.0,0.00
3829,1024,100,000000000000000021,0000000000,100_000000000000000021_1024_0000000000,11.0,0.00
3830,1024,100,000000000000000021,00000D1024,100_000000000000000021_1024_00000D1024,-11.0,0.00
5930,1031,100,000000000000000021,0000000000,100_000000000000000021_1031_0000000000,263.0,0.00
5931,1031,100,000000000000000021,00000C1032,100_000000000000000021_1031_00000C1032,7.0,0.00
5932,1031,100,000000000000000021,00000C1431,100_000000000000000021_1031_00000C1431,20.0,0.00
5933,1031,100,000000000000000021,00000D1031,100_000000000000000021_1031_00000D1031,-291.0,0.00
7515,1032,100,000000000000000021,0000000000,100_000000000000000021_1032_0000000000,7.0,0.00
7516,1032,100,000000000000000021,00000C1031,100_000000000000000021_1032_00000C1031,-7.0,0.00
8588,1034,100,000000000000000021,0000000000,100_000000000000000021_1034_0000000000,10.0,0.00
8589,1034,100,000000000000000021,00000D1034,100_000000000000000021_1034_00000D1034,2.0,0.00
9762,1037,100,000000000000000021,0000000000,100_000000000000000021_1037_0000000000,15.0,0.00
9763,1037,100,000000000000000021,00000D1037,100_000000000000000021_1037_00000D1037,-15.0,0.00
9918,1038,100,000000000000000021,0000000000,100_000000000000000021_1038_0000000000,86.0,0.00
9919,1038,100,000000000000000021,00000D1038,100_000000000000000021_1038_00000D1038,-86.0,0.00
10981,1041,100,000000000000000021,0000000000,100_000000000000000021_1041_0000000000,23.0,0.00
10982,1041,100,000000000000000021,00000D1041,100_000000000000000021_1041_00000D1041,-262.0,0.00
12395,1043,100,000000000000000021,0000000000,100_000000000000000021_1043_0000000000,22.0,0.00
12396,1043,100,000000000000000021,00000D1043,100_000000000000000021_1043_00000D1043,-24.0,0.00
12397,1043,100,000000000000000021,0001028224,100_000000000000000021_1043_0001028224,2.0,0.00
14048,1051,100,000000000000000021,0000000000,100_000000000000000021_1051_0000000000,4310.0,0.00
14049,1051,100,000000000000000021,0000011304,100_000000000000000021_1051_0000011304,-80.0,0.00
14050,1051,100,000000000000000021,0000014820,100_000000000000000021_1051_0000014820,-30.0,0.00
14051,1051,100,000000000000000021,00000C1051,100_000000000000000021_1051_00000C1051,-36.0,0.00
14052,1051,100,000000000000000021,00000C1053,100_000000000000000021_1051_00000C1053,90.0,0.00
14053,1051,100,000000000000000021,00000C1055,100_000000000000000021_1051_00000C1055,60.0,0.00
14054,1051,100,000000000000000021,00000C1121,100_000000000000000021_1051_00000C1121,-4.0,0.00
14055,1051,100,000000000000000021,00000D1051,100_000000000000000021_1051_00000D1051,-7262.0,0.00
14056,1051,100,000000000000000021,0001025501,100_000000000000000021_1051_0001025501,-6.0,0.00
14057,1051,100,000000000000000021,0001104122,100_000000000000000021_1051_0001104122,12.0,0.00
14058,1051,100,000000000000000021,0001110271,100_000000000000000021_1051_0001110271,14.0,0.00
14059,1051,100,000000000000000021,0002101560,100_000000000000000021_1051_0002101560,129.0,1806.21
14060,1051,100,000000000000000021,0002102188,100_000000000000000021_1051_0002102188,6.0,0.00
14061,1051,100,000000000000000021,0002103478,100_000000000000000021_1051_0002103478,112.0,1720.00
14062,1051,100,000000000000000021,0002104042,100_000000000000000021_1051_0002104042,44.0,0.00
14063,1051,100,000000000000000021,0002104043,100_000000000000000021_1051_0002104043,58.0,0.00
14064,1051,100,000000000000000021,0002104135,100_000000000000000021_1051_0002104135,2.0,0.00
14065,1051,100,000000000000000021,0002104206,100_000000000000000021_1051_0002104206,12.0,0.00
14066,1051,100,000000000000000021,0002104217,100_000000000000000021_1051_0002104217,20.0,0.00
14067,1051,100,000000000000000021,0002104268,100_000000000000000021_1051_0002104268,50.0,0.00
14068,1051,100,000000000000000021,0002104269,100_000000000000000021_1051_0002104269,4.0,0.00
14069,1051,100,000000000000000021,0002104275,100_000000000000000021_1051_0002104275,252.0,0.00
14070,1051,100,000000000000000021,0002104426,100_000000000000000021_1051_0002104426,10.0,0.00
14071,1051,100,000000000000000021,0002104614,100_000000000000000021_1051_0002104614,70.0,0.00
14072,1051,100,000000000000000021,0002104873,100_000000000000000021_1051_0002104873,39.0,0.00
14073,1051,100,000000000000000021,0002104984,100_000000000000000021_1051_0002104984,42.0,0.00
14074,1051,100,000000000000000021,0002105230,100_000000000000000021_1051_0002105230,4.0,0.00
14075,1051,100,000000000000000021,0002105672,100_000000000000000021_1051_0002105672,22.0,0.00
14076,1051,100,000000000000000021,0002105773,100_000000000000000021_1051_0002105773,4.0,0.00
14077,1051,100,000000000000000021,0002105815,100_000000000000000021_1051_0002105815,312.0,0.00
14078,1051,100,000000000000000021,0002106065,100_000000000000000021_1051_0002106065,14.0,0.00
14079,1051,100,000000000000000021,0002106532,100_000000000000000021_1051_0002106532,10.0,0.00
14080,1051,100,000000000000000021,0002107190,100_000000000000000021_1051_0002107190,119.0,0.00
14081,1051,100,000000000000000021,0002107392,100_000000000000000021_1051_0002107392,8.0,0.00
14082,1051,100,000000000000000021,0002107480,100_000000000000000021_1051_0002107480,8.0,0.00
14083,1051,100,000000000000000021,0002107766,100_000000000000000021_1051_0002107766,18.0,0.00
14084,1051,100,000000000000000021,0003100954,100_000000000000000021_1051_0003100954,192.0,0.00
14085,1051,100,000000000000000021,0003101696,100_000000000000000021_1051_0003101696,124.0,2322.00
14086,1051,100,000000000000000021,0003568968,100_000000000000000021_1051_0003568968,-8.0,0.00
14639,1053,100,000000000000000021,0000000000,100_000000000000000021_1053_0000000000,175.0,0.00
14640,1053,100,000000000000000021,00000C1051,100_000000000000000021_1053_00000C1051,-90.0,0.00
14641,1053,100,000000000000000021,00000D1053,100_000000000000000021_1053_00000D1053,7.0,0.00
14642,1053,100,000000000000000021,0003101244,100_000000000000000021_1053_0003101244,193.0,0.00
14833,1054,100,000000000000000021,0000000000,100_000000000000000021_1054_0000000000,35.0,0.00
14834,1054,100,000000000000000021,00000C1054,100_000000000000000021_1054_00000C1054,11.0,0.00
14835,1054,100,000000000000000021,00000D1054,100_000000000000000021_1054_00000D1054,-103.0,0.00
14836,1054,100,000000000000000021,0002103739,100_000000000000000021_1054_0002103739,50.0,0.00
14837,1054,100,000000000000000021,0002104349,100_000000000000000021_1054_0002104349,74.0,0.00
14838,1054,100,000000000000000021,0002104434,100_000000000000000021_1054_0002104434,2.0,0.00
14839,1054,100,000000000000000021,0002104936,100_000000000000000021_1054_0002104936,2.0,0.00
14840,1054,100,000000000000000021,0002105047,100_000000000000000021_1054_0002105047,20.0,0.00
14841,1054,100,000000000000000021,0002105330,100_000000000000000021_1054_0002105330,30.0,0.00
14842,1054,100,000000000000000021,0002105504,100_000000000000000021_1054_0002105504,10.0,0.00
14843,1054,100,000000000000000021,0002105738,100_000000000000000021_1054_0002105738,6.0,0.00
14844,1054,100,000000000000000021,0002108135,100_000000000000000021_1054_0002108135,4.0,0.00
14845,1054,100,000000000000000021,0003100518,100_000000000000000021_1054_0003100518,24.0,0.00
15107,1055,100,000000000000000021,0000000000,100_000000000000000021_1055_0000000000,43.0,0.00
15108,1055,100,000000000000000021,00000C1051,100_000000000000000021_1055_00000C1051,-60.0,0.00
15109,1055,100,000000000000000021,00000D1055,100_000000000000000021_1055_00000D1055,-9.0,0.00
15110,1055,100,000000000000000021,0001107317,100_000000000000000021_1055_0001107317,78.0,0.00
16358,1062,100,000000000000000021,0000000000,100_000000000000000021_1062_0000000000,91.0,0.00
16359,1062,100,000000000000000021,00000D1062,100_000000000000000021_1062_00000D1062,-15.0,0.00
17652,1065,100,000000000000000021,0000000000,100_000000000000000021_1065_0000000000,3.0,0.00
17653,1065,100,000000000000000021,00000D1065,100_000000000000000021_1065_00000D1065,-3.0,0.00
18394,1067,100,000000000000000021,0000000000,100_000000000000000021_1067_0000000000,16.0,0.00
18395,1067,100,000000000000000021,00000D1067,100_000000000000000021_1067_00000D1067,21.0,0.00
19281,1073,100,000000000000000021,0000000000,100_000000000000000021_1073_0000000000,290.0,0.00
22875,1121,100,000000000000000021,0000000000,100_000000000000000021_1121_0000000000,1068.0,0.00
22876,1121,100,000000000000000021,00000C1051,100_000000000000000021_1121_00000C1051,4.0,0.00
22877,1121,100,000000000000000021,00000D1121,100_000000000000000021_1121_00000D1121,-1072.0,0.00
24082,1151,100,000000000000000021,0000000000,100_000000000000000021_1151_0000000000,22829.0,0.00
24083,1151,100,000000000000000021,00000D1151,100_000000000000000021_1151_00000D1151,-22829.0,0.00
24375,1154,100,000000000000000021,0000000000,100_000000000000000021_1154_0000000000,-16.0,0.00
24376,1154,100,000000000000000021,00000D1154,100_000000000000000021_1154_00000D1154,-32.0,0.00
24377,1154,100,000000000000000021,0002102281,100_000000000000000021_1154_0002102281,70.0,0.00
24378,1154,100,000000000000000021,0002108375,100_000000000000000021_1154_0002108375,76.0,0.00
25759,1231,100,000000000000000021,0000000000,100_000000000000000021_1231_0000000000,13.0,0.00
25760,1231,100,000000000000000021,00000D1231,100_000000000000000021_1231_00000D1231,-13.0,0.00
25922,1331,100,000000000000000021,0000000000,100_000000000000000021_1331_0000000000,112.0,0.00
25923,1331,100,000000000000000021,00000D1331,100_000000000000000021_1331_00000D1331,-112.0,0.00
26473,1431,100,000000000000000021,0000000000,100_000000000000000021_1431_0000000000,20.0,0.00
26474,1431,100,000000000000000021,00000C1031,100_000000000000000021_1431_00000C1031,-20.0,0.00
26646,1521,100,000000000000000021,0000000000,100_000000000000000021_1521_0000000000,-290.0,0.00
26647,1521,100,000000000000000021,00000D1521,100_000000000000000021_1521_00000D1521,290.0,0.00
26939,1721,100,000000000000000021,0000000000,100_000000000000000021_1721_0000000000,-515.0,0.00
26940,1721,100,000000000000000021,00000D1721,100_000000000000000021_1721_00000D1721,515.0,0.00

In [23]:
resultZTMM004_1027 = pd.merge(left=dfZTMM004_SAPECC
                              , right=dfZTMM004_SAPBW
                              , left_on='Chave'
                              , right_on='Chave' 
                              , how='left'
                                    )

resultZTMM004_1027.rename(columns={'Qtd_x':'Qtd_SAPBW'
                                   ,'Qtd_y':'Qtd_SAPECC'
                                   ,'Vlr_x':'Vlr_SAPBW'
                                   ,'Vlr_y':'Vlr_SAPECC'
                                   ,'CodContaCorrente_x':'CodContaCorrente'
                                   ,'CodMaterial_x':'CodMaterial'
                                   ,'CodCentro_x':'CodCentro'
                                   ,'CodCliente_x':'CodCliente'},inplace=True)



# ETAPA DE COMPARAÇÃO COM OS DADOS DO SAP BW E OS DADOS DO SAP ECC - Coluna Quantidade
resultZTMM004_1027.loc[resultZTMM004_1027['Qtd_SAPBW'] == resultZTMM004_1027['Qtd_SAPECC'], 'Comparacao_Qtd'] = 'Igual'
resultZTMM004_1027.loc[resultZTMM004_1027['Qtd_SAPBW'] != resultZTMM004_1027['Qtd_SAPECC'], 'Comparacao_Qtd'] = 'Diferente'

# ETAPA DE COMPARAÇÃO COM OS DADOS DO SAP BW E OS DADOS DO SAP ECC - Coluna Valor
resultZTMM004_1027.loc[resultZTMM004_1027['Vlr_SAPBW'] == resultZTMM004_1027['Vlr_SAPECC'], 'Comparacao_Vlr'] = 'Igual'
resultZTMM004_1027.loc[resultZTMM004_1027['Vlr_SAPBW'] != resultZTMM004_1027['Vlr_SAPECC'], 'Comparacao_Vlr'] = 'Diferente'

resultComparacao_ZTMM004_1027 = resultZTMM004_1027[['Chave'
                                                    ,'CodContaCorrente'
                                                    ,'CodMaterial'
                                                    ,'CodCentro'
                                                    ,'CodCliente'
                                                    ,'Qtd_SAPBW'
                                                    ,'Qtd_SAPECC'
                                                    ,'Comparacao_Qtd'
                                                    ,'Vlr_SAPBW'
                                                    ,'Vlr_SAPECC'
                                                    ,'Comparacao_Vlr']]

In [24]:
dfZTMM004_SAPECC[(dfZTMM004_SAPECC['CodContaCorrente']=='013')
                & (dfZTMM004_SAPECC['CodCentro']=='1011')
                & (dfZTMM004_SAPECC['CodMaterial']=='000000000000000024')
                & (dfZTMM004_SAPECC['CodCliente']=='00000C1111')
                ]

# 013_000000000000000024_1011_00000C1111

#.sort_values(by='CodCliente')

,CodCentro,CodContaCorrente,CodMaterial,CodCliente,Chave,Qtd,Vlr
414,1011,013,000000000000000024,00000C1111,013_000000000000000024_1011_00000C1111,720.0,414317.8

In [25]:
dfZTMM004_SAPBW[(dfZTMM004_SAPBW['CodContaCorrente']=='013')
                & (dfZTMM004_SAPBW['CodCentro']=='1011')
                & (dfZTMM004_SAPBW['CodMaterial']=='000000000000000024')
                & (dfZTMM004_SAPBW['CodCliente']=='00000C1111')
                ]

,CodCentro,CodContaCorrente,CodMaterial,CodCliente,Chave,Qtd,Vlr
417,1011,013,000000000000000024,00000C1111,013_000000000000000024_1011_00000C1111,720.0,414317.8

In [26]:
resultComparacao_ZTMM004_1027[(resultComparacao_ZTMM004_1027['Comparacao_Qtd']=='Diferente')  
                              & (resultComparacao_ZTMM004_1027['CodContaCorrente']=='016')][['Chave'
                                                                                             ,'CodContaCorrente'
                                                                                             ,'CodMaterial'
                                                                                             ,'CodCentro'
                                                                                             ,'CodCliente'
                                                                                             ,'Qtd_SAPBW'
                                                                                             ,'Qtd_SAPECC'
                                                                                             ,'Comparacao_Qtd']].info()
#.to_csv('ZTMM004_Diferenca_Coluna_QUANTITY.csv', index=False, sep=';')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Chave             0 non-null      object
 1   CodContaCorrente  0 non-null      object
 2   CodMaterial       0 non-null      object
 3   CodCentro         0 non-null      object
 4   CodCliente        0 non-null      object
 5   Qtd_SAPBW         0 non-null      float64
 6   Qtd_SAPECC        0 non-null      float64
 7   Comparacao_Qtd    0 non-null      object
dtypes: float64(2), object(6)
memory usage: 0.0+ bytes

In [27]:
#resultComparacao_ZTMM004_1027[(resultComparacao_ZTMM004_1027['CodContaCorrente']=='002') 
#                & (resultComparacao_ZTMM004_1027['CodMaterial']=='000000000000000021')]

dfZTMM004_SAPECC[(dfZTMM004_SAPECC['Chave']=='013_000000000000000024_1011_00000C1111')]

,CodCentro,CodContaCorrente,CodMaterial,CodCliente,Chave,Qtd,Vlr
414,1011,013,000000000000000024,00000C1111,013_000000000000000024_1011_00000C1111,720.0,414317.8

In [28]:
#resultComparacao_ZTMM004_1027[(resultComparacao_ZTMM004_1027['CodContaCorrente']=='002') 
#                & (resultComparacao_ZTMM004_1027['CodMaterial']=='000000000000000021')]

dfZTMM004_SAPBW[(dfZTMM004_SAPBW['Chave']=='013_000000000000000024_1011_00000C1111')]

,CodCentro,CodContaCorrente,CodMaterial,CodCliente,Chave,Qtd,Vlr
417,1011,013,000000000000000024,00000C1111,013_000000000000000024_1011_00000C1111,720.0,414317.8

In [32]:
resultComparacao_ZTMM004_1027[(resultComparacao_ZTMM004_1027['Comparacao_Vlr']=='Igual') & (resultComparacao_ZTMM004_1027['CodContaCorrente']!='016')][['Chave'
                                                                                             ,'CodContaCorrente'
                                                                                             ,'CodMaterial'
                                                                                             ,'CodCentro'
                                                                                             ,'CodCliente'
                                                                                             ,'Vlr_SAPBW'
                                                                                             ,'Vlr_SAPECC'
                                                                                             ,'Comparacao_Vlr']]
#.to_csv('ZTMM004_Diferenca_Coluna_AMOUNT.csv', index=False, sep=';')

,Chave,CodContaCorrente,CodMaterial,CodCentro,CodCliente,Vlr_SAPBW,Vlr_SAPECC,Comparacao_Vlr
0,003_000000000000000024_1011_0000070950,003,000000000000000024,1011,0000070950,0.0,0.0,Igual
1,003_000000000000000024_1011_0000072169,003,000000000000000024,1011,0000072169,0.0,0.0,Igual
2,003_000000000000000024_1011_0000075518,003,000000000000000024,1011,0000075518,0.0,0.0,Igual
3,003_000000000000000024_1011_0000076015,003,000000000000000024,1011,0000076015,0.0,0.0,Igual
4,003_000000000000000024_1011_0000076303,003,000000000000000024,1011,0000076303,0.0,0.0,Igual
...,...,...,...,...,...,...,...,...
26497,100_000000000000000024_1821_00000C1098,100,000000000000000024,1821,00000C1098,0.0,0.0,Igual
26498,100_000000000000000024_1821_00000C1121,100,000000000000000024,1821,00000C1121,0.0,0.0,Igual
26499,100_000000000000000026_1821_00000C1121,100,000000000000000026,1821,00000C1121,0.0,0.0,Igual
26500,100_000000000000000027_1821_0000000000,100,000000000000000027,1821,0000000000,0.0,0.0,Igual
26501,100_000000000000000027_1821_00000C1012,100,000000000000000027,1821,00000C1012,0.0,0.0,Igual

In [30]:
resultComparacao_ZTMM004_1027[resultComparacao_ZTMM004_1027['Comparacao_Qtd'] =='Diferente'].groupby(['CodContaCorrente']).agg(QtdComp=('CodContaCorrente','count'))

Empty DataFrame
Columns: [QtdComp]
Index: []

In [33]:
resultComparacao_ZTMM004_1027[['CodContaCorrente'
                               ,'CodMaterial'
                               ,'CodCentro'
                               ,'CodCliente'
                               ,'Qtd_SAPBW'
                               ,'Vlr_SAPBW']].to_csv('C:\\Temp\\ZTMM004_CCV\\arquivo_ZTMM004_SAPBW.csv',sep=';',index=False)