In [1]:
import pandas as pd
import sqlalchemy
import pymysql

usuario = 'shvuser'
senha = 'IAn8DNWUKb'
ip_servidor = '172.31.37.131'
#ip_servidor = 'prod-shv-2022.cxplkxcmxyha.us-east-1.rds.amazonaws.com'
porta = '3306'
banco = 'LUMIS_SUPER'

enginemysql = sqlalchemy.create_engine(f'mysql+pymysql://{usuario}:{senha}@{ip_servidor}:{porta}/{banco}')

df = pd.read_sql_table('sgi_condominio',enginemysql)

,id,codigo,centro,nome,logradouro,numero,complemento,bairro,cep,cidade,uf,origem,data_criacao,ultima_atualizacao,id_sales_force,planilha_enviada,data_envio_planilha,cnpj,flag_ativo
0,1,1157423,C2A,CONDOMINIO EDIFICIO ANTARES;,RUA MADRE BARBARA MAIX,365.0,,JARDIM ITU SABARA,91225200,PORTO ALEGRE,RS,SAP CCS,2020-08-27 07:01:24,2020-08-27 07:01:24,None,None,NaT,None,S
1,2,1886797,C2A,CONDOMINIO MONTPELIER;,RUA FELIPE DE OLIVEIRA,1260.0,,PETROPOLIS,90630000,PORTO ALEGRE,RS,SAP CCS,2019-11-11 01:19:03,2019-11-11 01:19:03,None,None,NaT,None,N
2,3,1889980,C2A,CONDOMINIO EDIFICIO NILO PECANHA;,AV DR NILO PECANHA,620.0,,PETROPOLIS,90470000,PORTO ALEGRE,RS,SAP CCS,2020-09-26 07:01:28,2020-09-26 07:01:28,None,None,NaT,None,S

In [2]:
df[df['codigo'].isin(['3835856'])]

,id,codigo,centro,nome,logradouro,numero,complemento,bairro,cep,cidade,uf,origem,data_criacao,ultima_atualizacao,id_sales_force,planilha_enviada,data_envio_planilha,cnpj,flag_ativo
4154,5573,3835856,C2A,GIUNCIONE INCORPORACOES LTDA;,RUA DALTRO FILHO,151.0,,VILA JARDIM,93220140,SAPUCAIA DO SUL,RS,SAP CCS,2022-05-20 07:00:57,2022-05-20 07:00:57,None,None,NaT,None,S