In [10]:
import json
import datetime
import pandas as pd
from simple_salesforce import Salesforce, SalesforceLogin, SFType

In [11]:
username='etlshv@supergasbras.com.br', 
password='Super2020', 
security_token='2yY5vNvSMICU35NLeEjGAqtSJ'

In [12]:
#loginInfo = json.load(open('login.json'))
username = username #loginInfo['username']
password = password #loginInfo['password']
security_token = security_token #loginInfo['security_token']
domain = 'login'

In [13]:
session_id, instance = SalesforceLogin(username='etlshv@supergasbras.com.br', password='Super2020', security_token='2yY5vNvSMICU35NLeEjGAqtSJ', domain=domain)
sf = Salesforce(instance=instance, session_id=session_id)

In [23]:

queryConsultaVendaAno = f""" SELECT Id
,Name
,Conta__c
,Bonificacao__c
,Canal__c
,Codigo_Cliente_SAP__c
,Codigo_do_Cliente_SAP__c
,Conta_Recebedor__c
,Desconto__c
,Margem_de_Vendas_Realizada_Ano_ton__c
,Preco_de_Venda_Realizado_Ano_ton__c
,Volume_Realizado_Ano_Granel_ton__c
,Volume_Realizado_Ano_Outros_toneladas__c
,Volume_Realizado_Ano_P13_ton__c
,Volume_Realizado_Ano_P20_ton__c
,Volume_Realizado_Ano_P45_ton__c
,Volume_Total_Ano_ton__c

FROM Movimentacao_de_Venda_Ano__c

WHERE Codigo_do_Cliente_SAP__c IN ('0003911973','0003895827','0001063275')

"""
sf_dataVendaAno = sf.query_all(queryConsultaVendaAno)

sf_dfVendaAno = pd.DataFrame(sf_dataVendaAno['records']).drop(columns='attributes')

sf_dfVendaAno

,Id,Name,Conta__c,Bonificacao__c,Canal__c,Codigo_Cliente_SAP__c,Codigo_do_Cliente_SAP__c,Conta_Recebedor__c,Desconto__c,Margem_de_Vendas_Realizada_Ano_ton__c,Preco_de_Venda_Realizado_Ano_ton__c,Volume_Realizado_Ano_Granel_ton__c,Volume_Realizado_Ano_Outros_toneladas__c,Volume_Realizado_Ano_P13_ton__c,Volume_Realizado_Ano_P20_ton__c,Volume_Realizado_Ano_P45_ton__c,Volume_Total_Ano_ton__c
0,a1L4z000007QKrjEAG,2022,0014z00001gZlneAAC,0.0,D2,0003895827,0003895827,0014z00001gZlneAAC,0.0,1327.582,7033.192,2.487,0.0,0.0,0.0,0.0,2.487
1,a1L4z000007Q9s3EAC,2021,0014z00001gZlneAAC,0.0,D2,0003895827,0003895827,0014z00001gZlneAAC,0.0,1047.234,6336.103,0.698,0.0,0.0,0.0,0.0,0.698
2,a1L4z000007QVPAEA4,2022,0014z00001hY0InAAK,0.0,D2,0003911973,0003911973,0014z00001hY0InAAK,0.0,1083.331,6160.000,1.201,0.0,0.0,0.0,0.0,1.201
3,a1L4z000007QXclEAG,2022,001F000000j7fmpIAA,0.0,D2,0001063275,0001063275,001F000000j7fmpIAA,0.0,1281.458,6913.196,7.004,0.0,0.0,0.0,0.0,7.004

In [26]:
queryConsultaVendaMes = f""" 
SELECT

Name
,Canal__c
,Volume_Mensal_Projetado_total_em_ton__c
,Volume_Realizado_Mes_em_toneladas__c
,Preco_de_Venda_Realizado__c
,Margem_de_Vendas_Realizada__c
,Desconto__c
,Bonificacao__c
,Volume_Realizado_Mes_P13_ton__c
,Volume_Realizado_Mes_P20_ton__c
,Codigo_do_Cliente_SAP_Recebedor__c
,Codigo_do_Cliente_SAP__c
,Conta_Recebedor__c
,Volume_Realizado_Mes_Granel_ton__c
,Volume_Realizado_Mes_Outros_ton__c
,Volume_Realizado_Mes_P45_ton__c

FROM Movimentacao_de_Venda__c

WHERE Codigo_do_Cliente_SAP__c IN ('0003911973','0003895827','0001063275') 
and Name in ('2022/05', '2022/03')
"""
sf_dataVendaMes = sf.query_all(queryConsultaVendaMes)

sf_dfVendaMes = pd.DataFrame(sf_dataVendaMes['records']).drop(columns='attributes')

sf_dfVendaMes

,Name,Canal__c,Volume_Mensal_Projetado_total_em_ton__c,Volume_Realizado_Mes_em_toneladas__c,Preco_de_Venda_Realizado__c,Margem_de_Vendas_Realizada__c,Desconto__c,Bonificacao__c,Volume_Realizado_Mes_P13_ton__c,Volume_Realizado_Mes_P20_ton__c,Codigo_do_Cliente_SAP_Recebedor__c,Codigo_do_Cliente_SAP__c,Conta_Recebedor__c,Volume_Realizado_Mes_Granel_ton__c,Volume_Realizado_Mes_Outros_ton__c,Volume_Realizado_Mes_P45_ton__c
0,2022/03,D2-Vd Direta Granel,1.320,0.660,12320.000,0.002,0.0,0.0,0.0,0.0,0003911973,0003911973,0014z00001hY0InAAK,0.660,0.0,0.0
1,2022/03,D2-Vd Direta Granel,0.330,0.330,7362.545,0.001,0.0,0.0,0.0,0.0,0003895827,0003895827,0014z00001gZlneAAC,0.330,0.0,0.0
2,2022/03,D2-Vd Direta Granel,0.720,0.720,6913.194,0.001,0.0,0.0,0.0,0.0,0001063275,0001063275,001F000000j7fmpIAA,0.720,0.0,0.0
3,2022/05,D2-Vd Direta Granel,1.426,0.660,14725.090,0.004,0.0,0.0,0.0,0.0,0003895827,0003895827,0014z00001gZlneAAC,0.660,0.0,0.0
4,2022/05,D2-Vd Direta Granel,32.120,3.663,55305.580,0.008,0.0,0.0,0.0,0.0,0001063275,0001063275,001F000000j7fmpIAA,3.663,0.0,0.0
5,2022/05,D2-Vd Direta Granel,0.585,0.541,6160.000,0.001,0.0,0.0,0.0,0.0,0003911973,0003911973,0014z00001hY0InAAK,0.541,0.0,0.0

In [ ]:
queryConsultaVendaMes = f""" 
SELECT 

Data_do_Abastecimento__c
,Volume_Realizado__c
,Preco_Realizado__c
,Granel_R_Ton__c
,P_13__c
,P_20__c
,P_45__c
,Codigo_do_Cliente_SAP_Recebedor__c
,Codigo_do_Cliente_SAP__c
,Codigo_do_Material__c
,Conta_Recebedor__c
,Embalagem__c
,Quantidade_Faturada__c
,V_PrecoItem__c
,V_PrecoTon__c
,Canal_de_Venda_SHV__c

FROM Venda_Dia__c
)"""
sf_dataVendaMes = sf.query_all(queryConsultaVendaMes)

sf_dfVendaMes = pd.DataFrame(sf_dataVendaMes['records']).drop(columns='attributes')

sf_dfVendaMes