In [1]:
import pandas as pd

In [10]:
arquivoSergio = 'C:\Temp\POC fato abastecimento 20220818.xlsx'

dfAbastecimentoSergio = pd.read_excel(arquivoSergio
                                      ,sheet_name='PercNivelTanque'
                                      ,skiprows=16
                                      ,usecols=[0,1,2,3,25]
                                      ,names=['CodRelatorio'
                                              ,'CodItem'
                                              ,'CodDocVenda'
                                              ,'NumItemDocVenda'
                                              ,'PercNivelTanque']
                                      ,dtype={'CodRelatorio' : 'str',
                                            'CodItem' : 'str',
                                            'CodDocVenda' : 'str',
                                            'NumItemDocVenda' : 'str',
                                            'PercNivelTanque' : 'float',
                                            }
                                      ,header=0)


dfAbastecimentoSergio['CodItem'] = pd.Series(dfAbastecimentoSergio['CodItem']).astype(str).str.zfill(6) 
dfAbastecimentoSergio['NumItemDocVenda'] = pd.Series(dfAbastecimentoSergio['NumItemDocVenda']).astype(str).str.zfill(6)
dfAbastecimentoSergio['CodDocVenda'] = pd.Series(dfAbastecimentoSergio['CodDocVenda']).astype(str).str.zfill(10)

dfAbastecimentoSergio['Chave'] = dfAbastecimentoSergio['CodRelatorio'] + '_' + \
                                    dfAbastecimentoSergio['CodItem'] + '_' + \
                                    dfAbastecimentoSergio['NumItemDocVenda'] + '_' + \
                                    dfAbastecimentoSergio['CodDocVenda']

In [23]:
arquivoNovaFato = 'C:\\Temp\\nova_fato.csv'

dfNovaFato = pd.read_csv(arquivoNovaFato
                        ,usecols=[0,1,2,3,25]
                        ,names=['CodRelatorio'
                                ,'CodItem'
                                ,'CodDocVenda'
                                ,'NumItemDocVenda'
                                ,'PercNivelTanque']
                        ,dtype={'CodRelatorio' : 'str',
                                'CodItem' : 'str',
                                'CodDocVenda' : 'str',
                                'NumItemDocVenda' : 'str',
                                'PercNivelTanque' : 'float',
                                }
                        ,header=0)

dfNovaFato['CodItem'] = pd.Series(dfNovaFato['CodItem']).astype(str).str.zfill(6) 
dfNovaFato['NumItemDocVenda'] = pd.Series(dfNovaFato['NumItemDocVenda']).astype(str).str.zfill(6)
dfNovaFato['CodDocVenda	'] = pd.Series(dfNovaFato['CodDocVenda']).astype(str).str.zfill(10)


dfNovaFato['Chave'] = dfNovaFato['CodRelatorio'] + '_' + \
                        dfNovaFato['CodItem'] + '_' + \
                        dfNovaFato['NumItemDocVenda'] + '_' + \
                        dfNovaFato['CodDocVenda'] 

#dfNovaFato

In [6]:
arquivoNovaFato = 'C:\\Temp\\nova_fato.csv'

dfNovaFato = pd.read_csv(arquivoNovaFato,header=0)

dfNovaFato[(dfNovaFato['CodRelatorio'] ==1009518621)]

,CodRelatorio,CodItem,CodDocVenda,NumItemDocVenda,CodDocFaturamento,CodItemDocFat,NomStatusRecusa,NomStatusOrdemVenda,CodClienteSiloRecProduto,CodClienteRecMercadoria,...,DtBaixaColetor,QtdEstoque,QtdAbastecida,PercNivelTanque,QtdEstoque_2,KF_KAPAZ,CodDFEstornado,CodTipoDocFat,DthBaixaColetor,HoraBaixaColetor
2553,1009518621,100,32431352,10,9026882535,10,A,Atendida,949374.0,949374,...,20220628.0,2539.8,930.0,85,2539.8,2988.0,NaN,ZGON,20220628.0,160811.0
56068,1009518621,40,32428723,10,9026910450,10,A,Atendida,3566033.0,3566033,...,20220628.0,385.9,141.0,85,385.9,454.0,NaN,ZGON,20220628.0,152058.0
98032,1009518621,140,32411306,10,9026861242,10,A,Atendida,3878044.0,3878044,...,20220628.0,544.8,200.0,60,544.8,908.0,NaN,ZGON,20220628.0,183153.0
103660,1009518621,60,32511258,10,9026908346,10,A,Atendida,3709844.0,3709844,...,20220628.0,1157.7,290.0,85,1157.7,1362.0,NaN,ZGON,20220628.0,125046.0
163915,1009518621,80,32430669,10,9026910453,10,A,Atendida,949374.0,949374,...,20220628.0,3386.4,921.0,68,3386.4,4980.0,NaN,ZGON,20220628.0,163717.0
169460,1009518621,20,32429497,10,9026899336,11,A,Atendida,1093795.0,1093795,...,20220628.0,1157.7,209.0,85,1157.7,1362.0,NaN,ZGON,20220628.0,143956.0
205848,1009518621,70,32482997,10,9026876512,10,A,Atendida,3809424.0,3809424,...,20220628.0,385.9,190.0,85,385.9,454.0,NaN,ZGON,20220628.0,144957.0
264326,1009518621,50,32428658,10,9026909098,10,A,Atendida,3597754.0,3597754,...,20220628.0,771.8,190.0,85,771.8,908.0,NaN,ZGON,20220628.0,172335.0
369118,1009518621,90,32415891,10,9026907568,10,A,Atendida,949374.0,949374,...,20220628.0,4233.0,501.0,85,4233.0,4980.0,NaN,ZGON,20220628.0,165522.0
407314,1009518621,10,32429496,10,9026899336,10,A,Atendida,1093795.0,1093795,...,20220628.0,1157.7,341.0,85,1157.7,1362.0,NaN,ZGON,20220628.0,143953.0
409570,1009518621,110,32335872,10,9026890571,10,A,Atendida,977309.0,977309,...,20220628.0,846.6,261.0,85,846.6,996.0,NaN,ZGON,20220628.0,132804.0
442488,1009518621,30,32429498,10,9026899336,12,A,Atendida,1093795.0,1093795,...,20220628.0,1157.7,294.0,85,1157.7,1362.0,NaN,ZGON,20220628.0,143958.0

In [12]:
#dfNovaFato[dfNovaFato['CodRelatorio']=='1009101197'].sort_values(by='CodItem')

In [13]:
arquivoFatoAbastecimentoPRD = 'C:\\Temp\\fato_abastecimento_prd.csv'

dfFatoAbastecimentoPRD = pd.read_csv(arquivoFatoAbastecimentoPRD
                        ,usecols=[0,1,2,3,4]
                        ,names=['CodRelatorio'
                                ,'CodItem'
                                ,'CodDocVenda'
                                ,'NumItemDocVenda'
                                ,'PercNivelTanque']
                        ,dtype={'CodRelatorio' : 'str',
                                'CodItem' : 'str',
                                'CodDocVenda' : 'str',
                                'NumItemDocVenda' : 'str',
                                'PercNivelTanque' : 'float',
                                }
                        ,header=0
                        ,sep=';')

dfFatoAbastecimentoPRD['CodItem'] = pd.Series(dfFatoAbastecimentoPRD['CodItem']).astype(str).str.zfill(6) 
dfFatoAbastecimentoPRD['NumItemDocVenda'] = pd.Series(dfFatoAbastecimentoPRD['NumItemDocVenda']).astype(str).str.zfill(6)
dfFatoAbastecimentoPRD['CodDocVenda'] = pd.Series(dfFatoAbastecimentoPRD['CodDocVenda']).astype(str).str.zfill(10)

dfFatoAbastecimentoPRD['Chave'] = dfFatoAbastecimentoPRD['CodRelatorio'] + '_' + \
                                    dfFatoAbastecimentoPRD['CodItem'] + '_' + \
                                    dfFatoAbastecimentoPRD['NumItemDocVenda'] + '_' + \
                                    dfFatoAbastecimentoPRD['CodDocVenda'] 


#dfFatoAbastecimentoPRD

In [24]:
result = pd.merge((pd.merge(left=dfAbastecimentoSergio
                      , right=dfNovaFato
                      , left_on='Chave'
                      , right_on='Chave'
                      , how='left')
                      )
                      , right=dfFatoAbastecimentoPRD
                      , left_on='Chave'
                      , right_on='Chave'
                      , how='left')[['Chave'
                                           ,'CodRelatorio_x'
                                           ,'CodItem_x'
                                           ,'CodDocVenda_x'
                                           ,'NumItemDocVenda_x'
                                           ,'PercNivelTanque_x'
                                           ,'PercNivelTanque_y'
                                           ,'PercNivelTanque']]

result.rename(columns={'CodRelatorio_x':'CodRelatorio'
                          ,'CodItem_x':'CodItem'
                          ,'CodDocVenda_x':'CodDocVenda'
                          ,'NumItemDocVenda_x':'NumItemDocVenda'
                          ,'PercNivelTanque_x':'PercNivelTanque_ARQ_SERGIO'
                          ,'PercNivelTanque_y':'PercNivelTanque_ARQ_NOVA_FATO'
                          ,'PercNivelTanque':'PercNivelTanque_FATO_PRD'},inplace=True)

result['PercNivelTanque_ARQ_SERGIO'].fillna(0,inplace=True)
result['PercNivelTanque_ARQ_NOVA_FATO'].fillna(0,inplace=True)
result['PercNivelTanque_FATO_PRD'].fillna(0,inplace=True)

result.loc[result['PercNivelTanque_ARQ_NOVA_FATO'] == result['PercNivelTanque_FATO_PRD'], 'Comparacao'] = 'Igual'
result.loc[result['PercNivelTanque_ARQ_NOVA_FATO'] != result['PercNivelTanque_FATO_PRD'], 'Comparacao'] = 'Diferente'

In [26]:
result.groupby(['Comparacao'],as_index=False).agg(Qtd=('Comparacao','count'))

  Comparacao    Qtd
0  Diferente   4372
1      Igual  95628

In [29]:
display(result[(result['Comparacao']=='Diferente') & (result['PercNivelTanque_ARQ_NOVA_FATO']!=0)])

,Chave,CodRelatorio,CodItem,CodDocVenda,NumItemDocVenda,PercNivelTanque_ARQ_SERGIO,PercNivelTanque_ARQ_NOVA_FATO,PercNivelTanque_FATO_PRD,Comparacao
7,1008817619_000220_000010_0029729720,1008817619,000220,0029729720,000010,0.0,85.0,0.0,Diferente
8,1008879198_000180_000010_0030028957,1008879198,000180,0030028957,000010,0.0,85.0,0.0,Diferente
9,1009032645_000010_000010_0030697777,1009032645,000010,0030697777,000010,0.0,85.0,0.0,Diferente
10,1009130577_000120_000010_0031066399,1009130577,000120,0031066399,000010,0.0,85.0,0.0,Diferente
11,1008934946_000020_000010_0030273678,1008934946,000020,0030273678,000010,0.0,85.0,0.0,Diferente
...,...,...,...,...,...,...,...,...,...
99605,1009085340_000350_000010_0030760746,1009085340,000350,0030760746,000010,0.0,80.0,0.0,Diferente
99606,1009017046_000350_000010_0030437438,1009017046,000350,0030437438,000010,0.0,80.0,0.0,Diferente
99852,1008978428_000080_000010_0030438025,1008978428,000080,0030438025,000010,0.0,85.0,0.0,Diferente
99883,1008907496_000120_000010_0030214825,1008907496,000120,0030214825,000010,0.0,85.0,0.0,Diferente
99884,1008844734_000130_000010_0029755709,1008844734,000130,0029755709,000010,0.0,85.0,0.0,Diferente